# ESTE COMPOSE É UTILIZADO APENAS PARA TESTES LOCAIS

networks:
  main:
    driver: bridge
    
services:

  db:
    image: postgres
    restart: always
    ports:
      - 5437:5432
    volumes:
      - ./pgdata:/var/lib/postgresql
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - main

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - main

    
